module.exports = {
  Core: require('./core'),
  // Services
  Service: require('./services/service'),
  AsyncEvents: require('./services/asyncevents'),
  AWSMixIn: require('./services/aws-mixin'),
  Binary: require('./services/binary'),
  Executor: require('./services/executor'),
  FileBinary: require('./services/filebinary'),
  Mailer: require('./services/mailer'),
  Authentication: require('./services/authentication'),
  S3Binary: require('./services/s3binary'),
  // Store
  Store: require('./stores/store'),
  DynamoDBStore: require('./stores/dynamodb'),
  FileStore: require('./stores/file'),
  MemoryStore: require('./stores/memory'),
  MongoDBStore: require('./stores/mongodb'),
  // Queues
  Queue: require('./queues/queueservice'),
  SQSQueue: require('./queues/sqsqueue'),
  MemoryQueue: require('./queues/memoryqueue'),
  // Policies
  OwnerPolicy: require('./policies/ownerpolicy'),
  // Models
  CoreModel: require('./models/coremodel'),
  Ident: require('./models/ident'),
  // Utils
  SecureCookie: require('./utils/cookie'),
  LambdaCaller: require('./utils/lambdacaller'),
  // Handler
  LambdaHandler: require('./handlers/lambda')
}