packages:
  - packages/*
  - sample-app
  - sample-apps/*
  # Exclude packages that are not yet ready
  - "!packages/async"
  - "!packages/gcp"
  - "!packages/kubernetes"
  - "!packages/elasticsearch"
  - "!packages/google-auth"
  - "!packages/postgres"
  - "!packages/otel"
  - "!packages/hawk"
  - "!packages/mongodb"
  - "!packages/amqp"
  - "!packages/aws"
