import type { CommandArgDefinition, CommandDefinition } from "@webda/compiler";
import type { Application } from "../application/application.js";
import type { AbstractService } from "./iservice.js";
import { useLog } from "@webda/workout";

/**
 * A service command target: which service provides the command and how.
 */
export interface ServiceCommandTarget {
  /** Service type name from webda.module.json (e.g., "Webda/HttpServer") */
  name: string;
  /** Method name to call on the service */
  method: string;
  /** Service type identifier */
  type: string;
}

/**
 * Merged command info from one or more services declaring the same command.
 */
export interface ServiceCommandInfo {
  /** Human-readable description for CLI help */
  description: string;
  /** Services that handle this command (all execute in dependency order) */
  services: ServiceCommandTarget[];
  /** Merged argument definitions from all services */
  args: { [name: string]: CommandArgDefinition };
  /** Merged capability requirements from all services declaring this command */
  requires: string[];
  /**
   * Lifecycle phase declared by each service providing this command, in the
   * same order as `services`. Values are one of:
   * - `"resolved"`: service declared phase "resolved" (e.g. via `@BuildCommand`).
   * - `"initialized"`: service declared phase "initialized".
   * - `undefined`: service did not declare a phase (treat as "initialized").
   *
   * The CLI dispatcher uses this to decide whether to skip `Core.init()`:
   * all-"resolved" → resolve-only; all-"initialized"/undefined → full init; mixed → error.
   */
  phases: Array<"resolved" | "initialized" | undefined>;
}

/**
 * Collect all CLI commands declared by services across all loaded modules.
 *
 * Scans the `moddas`, `beans`, and `deployers` sections of `webda.module.json`
 * for services that have `commands` metadata (generated by the `@Command` decorator
 * at compile time). Merges commands from multiple services that declare the same
 * command name — each service becomes an entry in the `services` array, and args
 * are merged (first definition wins for each arg name).
 *
 * @param app - The loaded Webda Application with module metadata available
 * @returns A map of command names to their merged definitions
 *
 * @example
 * ```typescript
 * const commands = collectServiceCommands(app);
 * // {
 * //   "serve": {
 * //     description: "Start the HTTP server",
 * //     services: [{ name: "Webda/HttpServer", method: "serve", type: "Webda/HttpServer" }],
 * //     args: { port: { type: "number", default: 18080, alias: "p" } }
 * //   }
 * // }
 * ```
 */
export function collectServiceCommands(app: Application): { [name: string]: ServiceCommandInfo } {
  const commands: { [name: string]: ServiceCommandInfo } = {};
  const modules = app.getModules();

  for (const section of ["moddas", "beans", "deployers"] as const) {
    for (const [typeName, metadata] of Object.entries(modules[section] || {})) {
      if (!metadata.commands) continue;
      for (const [cmdName, cmdDef] of Object.entries(metadata.commands)) {
        commands[cmdName] ??= {
          description: cmdDef.description,
          services: [],
          args: { ...cmdDef.args },
          requires: [],
          phases: []
        };
        commands[cmdName].services.push({
          name: typeName,
          method: cmdDef.method,
          type: typeName
        });
        commands[cmdName].phases.push(cmdDef.phase);
        // Merge args from multiple services providing the same command
        for (const [argName, argDef] of Object.entries(cmdDef.args)) {
          commands[cmdName].args[argName] ??= argDef;
        }
        // Merge requires (union, no duplicates)
        for (const req of cmdDef.requires || []) {
          if (!commands[cmdName].requires.includes(req)) {
            commands[cmdName].requires.push(req);
          }
        }
      }
    }
  }

  return commands;
}

/**
 * Execute a CLI command by dispatching to all services that declared it.
 *
 * Services are executed in the order they were initialized (which follows the
 * dependency graph). The `serviceFilter` filters to specific services by name
 * (supports suffix matching).
 *
 * Each service's command handler is called with the parsed arguments as
 * positional parameters.
 *
 * @param cmdName - The command name to execute (e.g., `"serve"`, `"migrate"`)
 * @param cmdInfo - The merged command definition from {@link collectServiceCommands}
 * @param args - Parsed argument values keyed by argument name
 * @param services - Map of service name to service instance (from Core.getServices())
 * @param serviceFilter - Optional list of service names to filter to (supports suffix matching)
 * @returns `0` on success, `1` if no services match the filter, a method is missing or no service instance ran
 *
 * @example
 * ```typescript
 * // Execute "migrate" on all services:
 * await executeServiceCommand("migrate", cmdInfo, { dryRun: true }, core.getServices());
 *
 * // Execute "migrate" on a specific service:
 * await executeServiceCommand("migrate", cmdInfo, { dryRun: true }, core.getServices(), ["PostgresMigrator"]);
 * ```
 */
export async function executeServiceCommand(
  cmdName: string,
  cmdInfo: ServiceCommandInfo,
  args: { [key: string]: any },
  services: { [key: string]: AbstractService },
  serviceFilter?: string[]
): Promise<number> {
  // Filter services if requested, by type (e.g. "HttpServer") or by instance name (e.g. a deployment unit)
  const filtered = serviceFilter && serviceFilter.length > 0;
  const typeMatches = (svc: ServiceCommandTarget) => !filtered || serviceFilter.some(f => svc.name.endsWith(f) || svc.name === f);
  const instanceMatches = (service: AbstractService) =>
    filtered && typeof service.getName === "function" && serviceFilter.includes(service.getName());

  // Build positional args from command arg definitions; an omitted argument keeps
  // its slot as undefined so the following ones stay in position
  const commandArgs: any[] = Object.keys(cmdInfo.args).map(argName =>
    args[argName] !== undefined ? args[argName] : cmdInfo.args[argName].default
  );

  // Count executed handlers: a command where every provider was skipped did nothing
  let executed = 0;
  // Long-running handlers (serve, worker) return a cancelable promise that stays
  // pending while they run: start them all, then wait for every one to settle.
  const running: PromiseLike<any>[] = [];
  // Execute each matching service handler. A single target type can map to
  // multiple configured instances (e.g. two HttpServer services on different
  // ports); dispatch to every instance whose constructor matches the type.
  let filterMatched = !filtered;
  for (const svc of cmdInfo.services) {
    let matches: AbstractService[] = [];
    // Direct lookup — works when the modda name is used verbatim as service key
    if (services[svc.name]) matches.push(services[svc.name]);
    // Plus every other configured instance of the same class
    const shortName = svc.type.split("/").pop();
    for (const [, instanceService] of Object.entries(services)) {
      if (!instanceService || matches.includes(instanceService)) continue;
      if (instanceService.constructor?.name === shortName) {
        matches.push(instanceService);
      }
    }
    if (!typeMatches(svc)) {
      matches = matches.filter(instanceMatches);
      if (matches.length === 0) continue;
    }
    filterMatched = true;
    if (matches.length === 0) {
      useLog("WARN", `Service '${svc.name}' not found, skipping`);
      continue;
    }
    for (const service of matches) {
      if (!service[svc.method]) {
        const instanceName = typeof service.getName === "function" ? service.getName() : svc.name;
        useLog("ERROR", `Method '${svc.method}' not found on service '${instanceName}'`);
        return 1;
      }
      const result = service[svc.method](...commandArgs);
      if (isCancelable(result)) {
        running.push(result);
      } else {
        await result;
      }
      executed++;
    }
  }

  if (!filterMatched) {
    useLog("ERROR", `No services match filter '${serviceFilter.join(",")}' for command '${cmdName}'`);
    return 1;
  }
  if (executed === 0) {
    useLog("ERROR", `No service instance found to run command '${cmdName}'`);
    return 1;
  }
  // Cancelling a long-running command (SIGINT, SIGTERM) is a clean stop
  await Promise.all(
    running.map(p =>
      Promise.resolve(p).catch(err => {
        if (err !== "Cancelled") {
          throw err;
        }
      })
    )
  );
  return 0;
}

/**
 * Whether a command handler returned a long-running cancelable promise
 * (CancelablePromise or CancelableLoopPromise)
 *
 * @param result - the handler result
 * @returns true if the result can be cancelled
 */
function isCancelable(result: any): result is PromiseLike<any> & { cancel: () => Promise<void> } {
  return typeof result?.then === "function" && typeof result?.cancel === "function";
}
