import type { CommandArgDefinition, CommandDefinition } from "@webda/compiler";
import type { Application } from "../application/application.js";
import type { AbstractService } from "./iservice.js";
import { useLog } from "@webda/workout";

/**
 * A service command target: which service provides the command and how.
 */
export interface ServiceCommandTarget {
  /** Service type name from webda.module.json (e.g., "Webda/HttpServer") */
  name: string;
  /** Method name to call on the service */
  method: string;
  /** Service type identifier */
  type: string;
}

/**
 * Merged command info from one or more services declaring the same command.
 */
export interface ServiceCommandInfo {
  /** Human-readable description for CLI help */
  description: string;
  /** Services that handle this command (all execute in dependency order) */
  services: ServiceCommandTarget[];
  /** Merged argument definitions from all services */
  args: { [name: string]: CommandArgDefinition };
}

/**
 * Collect all CLI commands declared by services across all loaded modules.
 *
 * Scans the `moddas`, `beans`, and `deployers` sections of `webda.module.json`
 * for services that have `commands` metadata (generated by the `@Command` decorator
 * at compile time). Merges commands from multiple services that declare the same
 * command name — each service becomes an entry in the `services` array, and args
 * are merged (first definition wins for each arg name).
 *
 * @param app - The loaded Webda Application with module metadata available
 * @returns A map of command names to their merged definitions
 *
 * @example
 * ```typescript
 * const commands = collectServiceCommands(app);
 * // {
 * //   "serve": {
 * //     description: "Start the HTTP server",
 * //     services: [{ name: "Webda/HttpServer", method: "serve", type: "Webda/HttpServer" }],
 * //     args: { port: { type: "number", default: 18080, alias: "p" } }
 * //   }
 * // }
 * ```
 */
export function collectServiceCommands(app: Application): { [name: string]: ServiceCommandInfo } {
  const commands: { [name: string]: ServiceCommandInfo } = {};
  const modules = app.getModules();

  for (const section of ["moddas", "beans", "deployers"] as const) {
    for (const [typeName, metadata] of Object.entries(modules[section] || {})) {
      if (!metadata.commands) continue;
      for (const [cmdName, cmdDef] of Object.entries(metadata.commands)) {
        commands[cmdName] ??= {
          description: cmdDef.description,
          services: [],
          args: { ...cmdDef.args }
        };
        commands[cmdName].services.push({
          name: typeName,
          method: cmdDef.method,
          type: typeName
        });
        // Merge args from multiple services providing the same command
        for (const [argName, argDef] of Object.entries(cmdDef.args)) {
          commands[cmdName].args[argName] ??= argDef;
        }
      }
    }
  }

  return commands;
}

/**
 * Execute a CLI command by dispatching to all services that declared it.
 *
 * Services are executed in the order they were initialized (which follows the
 * dependency graph). The `serviceFilter` filters to specific services by name
 * (supports suffix matching).
 *
 * Each service's command handler is called with the parsed arguments as
 * positional parameters.
 *
 * @param cmdName - The command name to execute (e.g., `"serve"`, `"migrate"`)
 * @param cmdInfo - The merged command definition from {@link collectServiceCommands}
 * @param args - Parsed argument values keyed by argument name
 * @param services - Map of service name to service instance (from Core.getServices())
 * @param serviceFilter - Optional list of service names to filter to (supports suffix matching)
 * @returns `0` on success, `1` if no services match the filter or a method is missing
 *
 * @example
 * ```typescript
 * // Execute "migrate" on all services:
 * await executeServiceCommand("migrate", cmdInfo, { dryRun: true }, core.getServices());
 *
 * // Execute "migrate" on a specific service:
 * await executeServiceCommand("migrate", cmdInfo, { dryRun: true }, core.getServices(), ["PostgresMigrator"]);
 * ```
 */
export async function executeServiceCommand(
  cmdName: string,
  cmdInfo: ServiceCommandInfo,
  args: { [key: string]: any },
  services: { [key: string]: AbstractService },
  serviceFilter?: string[]
): Promise<number> {
  // Filter services if requested
  let targetServices = cmdInfo.services;
  if (serviceFilter && serviceFilter.length > 0) {
    targetServices = targetServices.filter(s =>
      serviceFilter.some(f => s.name.endsWith(f) || s.name === f)
    );
    if (targetServices.length === 0) {
      useLog("ERROR", `No services match filter '${serviceFilter.join(",")}' for command '${cmdName}'`);
      return 1;
    }
  }

  // Build positional args from command arg definitions
  const commandArgs: any[] = [];
  for (const argName of Object.keys(cmdInfo.args)) {
    if (args[argName] !== undefined) {
      commandArgs.push(args[argName]);
    } else if (cmdInfo.args[argName].default !== undefined) {
      commandArgs.push(cmdInfo.args[argName].default);
    }
  }

  // Execute each matching service handler
  for (const svc of targetServices) {
    // Try direct lookup first (works for beans and configured services)
    let service = services[svc.name];
    if (!service) {
      // Search through all services for ones matching the type by class name
      const shortName = svc.type.split("/").pop();
      for (const [, instanceService] of Object.entries(services)) {
        if (instanceService?.constructor?.name === shortName) {
          service = instanceService;
          break;
        }
      }
    }
    if (!service) {
      useLog("WARN", `Service '${svc.name}' not found, skipping`);
      continue;
    }
    if (!service[svc.method]) {
      useLog("ERROR", `Method '${svc.method}' not found on service '${svc.name}'`);
      return 1;
    }
    await service[svc.method](...commandArgs);
  }

  return 0;
}
