/// <reference types="@webda/core" />
import "@webda/core";
import type { Attributes } from "@webda/tsc-esm";
// This file is automatically generated by Webda CLI, do not edit it manually.
import type { ModelRefWithCreate } from "@webda/models";
declare module "@webda/core" {
  interface OperationContext<T = any, R = any> {
    action: Operation;
  }

  interface MemoryLoggerService {
    parameters: {
        get limit(): 100;
        set limit(v: number);
    }
  }

  type services = {
    customService: import("./src/services/custom").CustomService;
    memorylogger: import("@webda/core").MemoryLoggerService;
    beanService: import("./src/services/bean").BeanService;
    customService2: import("./src/services/custom").CustomService<CustomParameters>;
  }

  type moddas = {
    "Webda/MemoryLogger": MemoryLoggerService;
    "sample-app/BeanService": BeanService;
    "sample-app/CustomService": CustomService;
    "sample-app/CustomService2": CustomService<CustomParameters>;
  }

  type models = {
    "User": import("./src/models/user").User;
    "Company": import("./src/models/company").Company;
    "Project": import("./src/models/project").Project;
    "AbstractProject": import("./src/models/project").AbstractProject<import("./src/models/project").TestDoc2>;
  }

  // Declare useService function overloads
  export function useService<T extends keyof services>(name: T): services[T];
  export function useService(name: Exclude<string, keyof services>): never;

  interface Application {
    // One conditional signature:
    getModda<N extends string>(
      name: N
    ): N extends keyof moddas ? moddas[N] : never;
    getModdas(): moddas;
    completeNamespace<T extends string>(info: T): T extends `${string}/${string}` ? T : `MyNamespace/${T}`;
    getModel<N extends string>(
      name: N
    ): N extends keyof models ? models[N] : never;
    getModels(): models;
    getWebdaVersion(): "4.0.0-beta.2";
  }

  interface Core {
    getService<T extends keyof services>(name: T): services[T];
    getService(name: Exclude<string, keyof services>): never;
    getServices(): services;
    getVersion(): "4.0.0-beta.2";
    getLocales(): ["en-gb"];
    getBeans(): Pick<services, "beanService">;
  }

  // Schema references
  // Operations
  // ModelActions
}
declare module "./src/models/project" {
    // interface ProjectConstructor {
    //     Actions: "create" | "read" | "update" | "delete" | "list";
    // }
    // const Project: ProjectConstructor;

    interface Project$ extends Omit<Project, "test"> {
        get test(): Date;
        set test(value: number | string | Date);     
        ref(): Omit<ModelRefMagic<Project$, Project$Params>, "create"| "upsert">;   
    }

    interface Project$Params {
        test: number | string | Date;
    }

    interface ModelRefMagic<T, K> extends ModelRefWithCreate<T> {
        patch: (data: Partial<K>) => Promise<void>;
        setAttribute<K extends Attributes<T>>(key: K, value: K extends keyof Project$Params ? Project$Params[K] : Project$[K]): Promise<void>;
        //setAttribute<K extends "test">(key: K, value: Project$Params[K]): Promise<void>;
    }

    namespace Project {
        const Actions: "create" | "read" | "update" | "delete" | "list";
        /**
         * Magic function to create model ref with helpers
         * @param uuid 
         */
        function $(uuid: string): ModelRefMagic<Project$, Project$Params>;
    }

    interface Project {
        toProxy(): Project$
    }
}

declare module "@webda/models" {

    interface ProjectHelper extends Omit<Project, "test"> {
        get test(): Date;
        set test(value: number | string | Date);
    }
    
    export type Helpers<T> = T extends Project ? ProjectHelper : T extends { toProxy(): infer R } ? R : T;
}