import { suite, test } from "@webda/test";
import * as assert from "assert";
import { CounterBehavior, CounterHolder } from "./behavior-fixture.model.js";

@suite
class BehaviorFixtureTest {
  @test
  hydratesBehavior() {
    // __hydrateBehaviors is generated by @webda/content-mapper; without the vite plugin it is absent
    assert.strictEqual(typeof (CounterHolder.prototype as any).__hydrateBehaviors, "function");
    const holder = new CounterHolder();
    (holder as any).__hydrateBehaviors({ counter: { count: 2 } });
    assert.ok(holder.counter instanceof CounterBehavior);
    assert.strictEqual(holder.counter.increment(), 3);
    assert.strictEqual((holder.counter as any).parent.instance, holder);
  }
}
