import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";
import { useLog } from "@webda/workout";

/**
 * Read `webda.config.json#session` (a model id like `MyApp/Session`),
 * resolve it via `webda.module.json` to an import path, and emit
 * `.webda/session-types.d.ts` with a module augmentation that fills the
 * `WebdaSessionRegistry["session"]` slot.
 *
 * The augmentation is a plain `.d.ts` file under the project — it is picked
 * up by `tsc` via the user's standard tsconfig include, so editor feedback
 * works without our ts-plugin loaded.
 *
 * @param projectRoot absolute path to the project root (where webda.config.json lives)
 */
export function generateSessionTypes(projectRoot: string): void {
  const configPath = join(projectRoot, "webda.config.json");
  if (!existsSync(configPath)) return;

  const config = JSON.parse(readFileSync(configPath, "utf-8")) as { session?: string };
  if (!config.session) return;

  const modulePath = join(projectRoot, "webda.module.json");
  if (!existsSync(modulePath)) {
    throw new Error(`Cannot resolve session model "${config.session}": webda.module.json is missing`);
  }

  const mod = JSON.parse(readFileSync(modulePath, "utf-8")) as {
    models?: { list?: Record<string, string> };
  };
  const models = mod.models?.list ?? {};

  const importDescriptor = resolveModelImport(models, config.session);
  if (!importDescriptor) {
    throw new Error(`Cannot resolve session model "${config.session}" in webda.module.json: not declared`);
  }

  const [importFile, exportName] = importDescriptor.split(":");
  const outDir = join(projectRoot, ".webda");
  if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true });
  const outPath = join(outDir, "session-types.d.ts");

  let importTarget: string;
  if (importFile.startsWith(".") || importFile.startsWith("/")) {
    const absImportFile = importFile.startsWith("/") ? importFile : join(projectRoot, importFile);
    importTarget = relative(outDir, absImportFile)
      .replace(/\\/g, "/")
      .replace(/\.tsx?$/, ".js");
    if (!importTarget.startsWith(".")) importTarget = "./" + importTarget;
  } else {
    importTarget = importFile;
  }

  const content =
    `// AUTO-GENERATED by @webda/compiler — do not edit\n` +
    `import type { ${exportName} as __ResolvedSession } from "${importTarget}";\n` +
    `declare module "@webda/core" {\n` +
    `  interface WebdaSessionRegistry {\n` +
    `    session: __ResolvedSession;\n` +
    `  }\n` +
    `}\n`;

  writeFileSync(outPath, content);
  useLog("INFO", `Generated session types at ${relative(projectRoot, outPath)}`);
}

/**
 * Look up a model id in the module's models list. Accepts both fully
 * qualified ids (`MyApp/Session`) and bare class names (`Session`); for the
 * latter, returns the first matching declaration.
 * @param models - the flat record of model ids to import descriptors from webda.module.json
 * @param id - the model id to look up (e.g. `MyApp/Session` or bare `Session`)
 * @returns the import descriptor string `"<file>:<ExportName>"`, or undefined if not found
 */
function resolveModelImport(models: Record<string, string>, id: string): string | undefined {
  if (models[id]) return models[id];
  if (!id.includes("/")) {
    for (const key of Object.keys(models)) {
      if (key.split("/").pop() === id) return models[key];
    }
  }
  return undefined;
}
