import type { PK, PrimaryKey, PrimaryKeyAttributes, PrimaryKeyType, ModelClass } from "../storable.js";
import type { Helpers, JSONed, NumericPropertyPaths, PropertyPaths, PropertyPathType, SelfJSONed } from "../types.js";
import { WEBDA_PRIMARY_KEY, WEBDA_EVENTS, WEBDA_LEGACY_UID } from "../storable.js";
import { ModelRefWithCreate } from "../relations.js";
import { Repository } from "./repository.js";
import type { ArrayElement } from "@webda/tsc-esm";
import type {
  AggregationQuery,
  AggregationResult,
  Assignment,
  Query as WebdaQLQuery,
  QueryParameters
} from "@webda/ql";
import type { AggregatedRow, AggregationOptions, AggregationSpec, MetricSpec } from "../aggregation.js";

/**
 * Base repository implementation providing shared logic for key management,
 * event handling, and default method implementations.
 *
 * Concrete repositories (MemoryRepository, etc.) extend this class and
 * implement the abstract storage methods.
 *
 * @typeParam T - The ModelClass this repository manages
 */
export abstract class AbstractRepository<T extends ModelClass> implements Repository<T> {
  /** Registered event listeners keyed by event name */
  protected events: Map<keyof InstanceType<T>[typeof WEBDA_EVENTS], Set<(data: any) => void>> = new Map();

  /** Aggregation fallback policy, set by the owning store through configureAggregation */
  protected aggregationOptions: AggregationOptions = { fallback: "warn", maxGroups: 10000 };
  /** Fallback shapes already warned about */
  protected warnedAggregations: Set<string> = new Set();

  /**
   * @param model - The model class constructor
   * @param pks - Array of primary key field names
   * @param separator - Separator used when joining composite key fields into a string (default: "_")
   */
  constructor(
    protected model: T,
    protected pks: string[],
    protected separator: string = "_"
  ) {}
  /** @override */
  getRootModel(): T {
    return this.model;
  }

  /**
   * Build the model instance to create from the incoming data
   *
   * Primary key fields that are undefined or null are dropped from the data so a
   * key generated by the model constructor (e.g. UuidModel) is not overwritten.
   * Repositories must read the storage key from the returned instance.
   *
   * @param data - the incoming data
   * @returns the model instance
   */
  protected buildItem(data: Helpers<InstanceType<T>>): InstanceType<T> {
    // An instance of the model is stored as is: copying it would drop the fields held in accessors
    if (data instanceof this.model) {
      return data as InstanceType<T>;
    }
    let input: any = data;
    if (input && this.pks.some(k => k in input && (input[k] === undefined || input[k] === null))) {
      input = { ...input };
      for (const k of this.pks) {
        if (input[k] === undefined || input[k] === null) {
          delete input[k];
        }
      }
    }
    // Build a fresh instance and copy the incoming fields onto it. Most model
    // constructors ignore their arguments (only RegistryEntry and a few others
    // assign them), so `new this.model(data)` alone would drop the fields.
    const item = new this.model(input) as InstanceType<T>;
    if (input && input !== item) {
      if (typeof (item as any).load === "function") {
        (item as any).load(input);
      } else {
        Object.assign(item as any, input);
      }
    }
    return item;
  }

  /**
   * Return a ref from the uuid
   * @param uid - the serialized primary key
   * @returns a model reference with create capability
   */
  fromUID(uid: string): ModelRefWithCreate<InstanceType<T>> {
    return this.ref(this.parseUID(uid));
  }

  /**
   * Parse a serialized primary key
   *
   * A composite key that does not split into the primary key fields is offered to the model's optional
   * `static parseLegacyUID(uid)` hook (see `WEBDA_LEGACY_UID`): the returned key keeps the raw uid as its
   * string form so it addresses the legacy storage entry. Without a hook, or when the hook declines, the
   * uid is rejected.
   * @override
   */
  parseUID(uid: string, forceObject?: boolean): PrimaryKeyType<InstanceType<T>> | PrimaryKey<InstanceType<T>> {
    if (this.pks.length === 1) {
      return forceObject
        ? ({ [this.pks[0]]: uid } as PrimaryKey<InstanceType<T>>)
        : (uid as PK<InstanceType<T>, InstanceType<T>[typeof WEBDA_PRIMARY_KEY][number]>);
    }
    const parts = uid.split(this.separator);
    if (parts.length !== this.pks.length) {
      const legacy = this.parseLegacyUID(uid);
      if (legacy) {
        return legacy;
      }
      throw new Error(`Invalid UID: ${uid}`);
    }
    const result = {} as PrimaryKey<InstanceType<T>>;
    for (let i = 0; i < this.pks.length; i++) {
      result[this.pks[i] as keyof InstanceType<T>] = parts[i] as any;
    }
    return result;
  }

  /**
   * Parse a uid through the model's `parseLegacyUID` hook
   * @param uid - the raw storage key
   * @returns a key whose string form is the raw uid, or undefined when the model does not recognise it
   */
  protected parseLegacyUID(uid: string): PrimaryKey<InstanceType<T>> | undefined {
    const parsed = (this.model as any)?.parseLegacyUID?.(uid);
    if (!parsed || typeof parsed !== "object") {
      return undefined;
    }
    const key: any = { ...parsed };
    Object.defineProperty(key, WEBDA_LEGACY_UID, { value: uid, enumerable: false });
    Object.defineProperty(key, "toString", { value: () => uid, enumerable: false });
    return key;
  }

  /** @override */
  excludePrimaryKey(object: any): any {
    const pkFields = (object.PrimaryKey || this.pks || []) as Array<keyof T>;
    const result = { ...object };
    for (const field of pkFields) {
      delete result[field];
    }
    return result;
  }

  /** Get the primary key value for an object as a scalar or string. */
  getPrimaryKey(object: any, forceObject?: false): PrimaryKeyType<InstanceType<T>>;
  /** Get the primary key value for an object as a structured key object. */
  getPrimaryKey(object: any, forceObject: true): PrimaryKey<InstanceType<T>>;
  /** @override */
  getPrimaryKey(object: any, forceObject?: boolean): PrimaryKeyType<InstanceType<T>> | PrimaryKey<InstanceType<T>> {
    if (object === undefined || object === null) {
      throw new Error("Cannot get primary key of undefined/null");
    }
    const pkFields = (object[WEBDA_PRIMARY_KEY] || this.pks || []) as Array<keyof InstanceType<T>>;
    if (pkFields.length === 0) {
      throw new Error("No primary key defined on model " + this.model?.name);
    }
    // Scalar value (string or number) — treat as the PK value directly
    if (typeof object === "string" || typeof object === "number") {
      if (pkFields.length === 1) {
        if (forceObject) {
          return { [pkFields[0]]: object, toString: () => object.toString() } as PK<T, any>;
        }
        return object as any;
      }
      // Composite key passed as string — parse it
      object = this.parseUID(object as string);
    }
    // A key parsed from a legacy uid already addresses its raw storage entry
    if (object[WEBDA_LEGACY_UID] !== undefined) {
      return object;
    }
    // Single PK field
    if (pkFields.length === 1) {
      const field = pkFields[0];
      const value = object[field];
      if (value !== undefined) {
        if (forceObject) {
          return { [field]: value, toString: () => value.toString() } as PK<T, any>;
        }
        return value as any;
      }
      // Value not found — try constructing the model to extract it
      if (this.model) {
        const instance = new this.model(object) as any;
        instance.load?.(object);
        const extracted = instance[field];
        if (extracted !== undefined) {
          if (forceObject) {
            return { [field]: extracted, toString: () => extracted.toString() } as PK<T, any>;
          }
          return extracted as any;
        }
      }
      throw new Error(`Missing primary key field '${String(field)}' on object`);
    }
    // Composite key — extract each field
    if (pkFields.some(f => object[f] === undefined) && this.model) {
      const instance = new this.model(object) as InstanceType<T>;
      (instance as any).load?.(object);
      object = instance;
    }
    if (pkFields.some(f => object[f] === undefined)) {
      throw new Error(`Missing primary key fields: ${pkFields.filter(f => object[f] === undefined).join(", ")}`);
    }

    // Build composite key object
    const key = pkFields.reduce((acc, field) => {
      (acc as any)[field] = object[field];
      return acc;
    }, {} as any);
    key.toString = () => {
      return Object.values(key)
        .filter(v => typeof v !== "function")
        .join(this.separator);
    };
    return key;
  }

  /** @override */
  getUID(object: any): string {
    return this.getPrimaryKey(object).toString();
  }

  /** @override */
  async upsert(data: Helpers<InstanceType<T>>): Promise<InstanceType<T>> {
    const key = this.getPrimaryKey(data);
    if (await this.exists(key)) {
      await this.patch(key, data as InstanceType<T>);
      return this.get(key) as InstanceType<T>;
    }
    return this.create(data);
  }

  /** @override */
  async setAttribute<K extends PropertyPaths<InstanceType<T>>, L extends PropertyPaths<InstanceType<T>>>(
    primaryKey: PK<InstanceType<T>, InstanceType<T>[typeof WEBDA_PRIMARY_KEY][number]> | string,
    attribute: K,
    value: PropertyPathType<InstanceType<T>, K>,
    conditionField?: L | null,
    condition?: PropertyPathType<InstanceType<T>, L> | JSONed<PropertyPathType<InstanceType<T>, L>>
  ): Promise<void> {
    return this.patch(this.getPrimaryKey(primaryKey), { [attribute]: value } as any, conditionField, condition);
  }

  /** @override */
  public ref(
    key: PK<InstanceType<T>, InstanceType<T>[typeof WEBDA_PRIMARY_KEY][number]>
  ): ModelRefWithCreate<InstanceType<T>> {
    return new ModelRefWithCreate<InstanceType<T>>(key, this as any);
  }

  /** @override */
  async incrementAttribute<K extends PropertyPaths<InstanceType<T>>, L extends NumericPropertyPaths<InstanceType<T>>>(
    primaryKey: PK<InstanceType<T>, InstanceType<T>[typeof WEBDA_PRIMARY_KEY][number]>,
    info: L | { property: L; value?: number },
    _conditionField?: K | null,
    _condition?: any
  ): Promise<void> {
    await this.incrementAttributes(primaryKey, [info as any]);
  }

  abstract incrementAttributes<
    K extends PropertyPaths<InstanceType<T>>,
    L extends NumericPropertyPaths<InstanceType<T>>
  >(
    primaryKey: PK<InstanceType<T>, InstanceType<T>[typeof WEBDA_PRIMARY_KEY][number]>,
    info: (L | { property: L; value?: number })[] | Record<L, number>,
    _conditionField?: K | null,
    _condition?: any
  ): Promise<void | Record<string, number>>;

  /**
   * Field paths of the model, from its metadata (`Reflection` and the stored, input and output schemas)
   *
   * Used to validate UPDATE SET targets.
   * @returns the field names, undefined when the model carries no field metadata (no validation then)
   */
  getAllowedFields(): string[] | undefined {
    const meta: any = (this.model as any)?.Metadata;
    const fields = new Set<string>([
      ...Object.keys(meta?.Reflection ?? {}),
      ...Object.keys(meta?.Schemas?.Stored?.properties ?? {}),
      ...Object.keys(meta?.Schemas?.Input?.properties ?? {}),
      ...Object.keys(meta?.Schemas?.Output?.properties ?? {})
    ]);
    return fields.size ? [...fields] : undefined;
  }

  /**
   * Parse a bulk statement and check it is of the expected type
   *
   * For an UPDATE, every SET target is checked: no primary key field, no private (`__`) segment, no
   * `constructor`/`prototype` segment, and a field of the model when its metadata lists them.
   * @param type - the expected statement type
   * @param statement - the statement string or its parsed form
   * @param params - values for the placeholders of a statement string
   * @returns the parsed statement
   * @throws WebdaQLError when the statement has another type or a SET target is refused
   * @throws SyntaxError when the statement does not parse, or a SET target is not a field of the model
   */
  protected async parseStatement(
    type: "DELETE" | "UPDATE",
    statement: string | WebdaQLQuery,
    params?: QueryParameters
  ): Promise<WebdaQLQuery> {
    const WebdaQL = await import("@webda/ql");
    let parsed: WebdaQLQuery;
    if (typeof statement === "string") {
      parsed = WebdaQL.parse(params !== undefined ? WebdaQL.bind(statement, params) : statement);
    } else {
      if (params !== undefined) {
        throw new WebdaQL.WebdaQLError("Parameters can only be bound to a statement string");
      }
      // A query object built or changed by code goes back through the grammar: no forged path, operator or value
      // reaches a backend
      parsed = WebdaQL.normalizeQuery(statement);
    }
    if (parsed.type !== type) {
      throw new WebdaQL.WebdaQLError(
        `${type === "DELETE" ? "deleteMany needs a" : "updateMany needs an"} ${type} statement, not ${parsed.type ?? "a filter"}`
      );
    }
    if (type === "UPDATE") {
      if (!parsed.assignments?.length) {
        throw new WebdaQL.WebdaQLError("UPDATE needs at least one SET assignment");
      }
      const targets = parsed.assignments.map(a => a.field);
      for (const field of targets) {
        const segments = field.split(".");
        if (segments.some(s => !/^[A-Za-z0-9_]+$/.test(s))) {
          throw new WebdaQL.WebdaQLError(`UPDATE cannot set the field '${field}': empty or invalid path segment`);
        }
        if (this.pks.includes(segments[0])) {
          throw new WebdaQL.WebdaQLError(`UPDATE cannot change the primary key field '${field}'`);
        }
        if (segments.some(s => s.startsWith("__") || s in Object.prototype || s === "prototype")) {
          throw new WebdaQL.WebdaQLError(`UPDATE cannot set the private field '${field}'`);
        }
        // The same field twice, or a field and one of its children: the result would depend on the store
        if (
          targets.some(other => other !== field && other.startsWith(`${field}.`)) ||
          targets.indexOf(field) !== targets.lastIndexOf(field)
        ) {
          throw new WebdaQL.WebdaQLError(`UPDATE sets '${field}' more than once`);
        }
      }
      const allowed = this.getAllowedFields();
      if (allowed) {
        WebdaQL.validateQueryFields(parsed, allowed);
      }
    }
    return parsed;
  }

  /**
   * Set the assignments of an UPDATE on an object, creating the intermediate objects of dotted paths
   *
   * Targets were checked by {@link parseStatement}: letters, digits and `_` only, no `__` segment, no
   * `Object.prototype` member name.
   * @param target - the object to change in place
   * @param assignments - the SET assignments
   * @returns the target
   */
  protected applyAssignments<O>(target: O, assignments: Assignment[]): O {
    for (const { field, value } of assignments) {
      const segments = field.split(".");
      let current: any = target;
      for (const segment of segments.slice(0, -1)) {
        if (current[segment] === null || typeof current[segment] !== "object") {
          current[segment] = {};
        }
        current = current[segment];
      }
      current[segments[segments.length - 1]] = value;
    }
    return target;
  }

  /**
   * Keys of the objects matching the WHERE of a statement, collected before any change so an update changing a
   * WHERE field cannot meet the same object twice; at most LIMIT keys
   * @param statement - the parsed statement
   * @returns the primary keys
   */
  protected async collectStatementKeys(statement: WebdaQLQuery): Promise<PrimaryKeyType<InstanceType<T>>[]> {
    const keys: PrimaryKeyType<InstanceType<T>>[] = [];
    if (statement.limit !== undefined && statement.limit <= 0) {
      return keys;
    }
    for await (const object of this.iterate(statement.filter.toString())) {
      keys.push(this.getPrimaryKey(object));
      if (statement.limit && keys.length >= statement.limit) {
        break;
      }
    }
    return keys;
  }

  /**
   * Run one write of the generic fallback; an object deleted since the keys were collected is skipped
   * @param key - the primary key
   * @param write - the write
   * @returns true when written, false when the object is gone
   * @throws the write error when the object still exists
   */
  protected async writeIfPresent(key: PrimaryKeyType<InstanceType<T>>, write: () => Promise<void>): Promise<boolean> {
    try {
      await write();
      return true;
    } catch (err) {
      if (await this.exists(key)) {
        throw err;
      }
      return false;
    }
  }

  /**
   * Generic `deleteMany`: collect the matching keys (up to LIMIT), then delete them one by one with this
   * repository's `delete` primitive
   *
   * Used by stores without a native bulk delete. On a store repository the primitive emits no event.
   * @param statement - the DELETE statement or its parsed form
   * @param params - values for the placeholders
   * @returns the number of objects deleted
   */
  protected async deleteManyByKey(statement: string | WebdaQLQuery, params?: QueryParameters): Promise<number> {
    const parsed = await this.parseStatement("DELETE", statement, params);
    const keys = await this.collectStatementKeys(parsed);
    let count = 0;
    for (const key of keys) {
      if (await this.writeIfPresent(key, () => this.delete(key))) count++;
    }
    return count;
  }

  /**
   * Generic `updateMany`: collect the matching keys (up to LIMIT), then patch them one by one with this
   * repository's `patch` primitive. A dotted target reads the object to rewrite its top-level field.
   *
   * Used by stores without a native bulk update. On a store repository the primitive emits no event.
   * @param statement - the UPDATE statement or its parsed form
   * @param params - values for the placeholders
   * @returns the number of objects updated
   */
  protected async updateManyByKey(statement: string | WebdaQLQuery, params?: QueryParameters): Promise<number> {
    const parsed = await this.parseStatement("UPDATE", statement, params);
    const keys = await this.collectStatementKeys(parsed);
    const nested = parsed.assignments!.some(a => a.field.includes("."));
    let count = 0;
    for (const key of keys) {
      const patch: any = {};
      if (nested) {
        let current: any;
        try {
          current = await this.get(key);
        } catch (err) {
          if (await this.exists(key)) throw err;
          // Deleted since the keys were collected
          continue;
        }
        for (const { field } of parsed.assignments!) {
          const top = field.split(".")[0];
          // A deep copy of the current value, so the nested assignments keep its other fields
          patch[top] ??= current?.[top] === undefined ? undefined : JSON.parse(JSON.stringify(current[top]));
        }
      }
      if (await this.writeIfPresent(key, () => this.patch(key, this.applyAssignments(patch, parsed.assignments!)))) {
        count++;
      }
    }
    return count;
  }

  /**
   * Delete in bulk: see {@link Repository.deleteMany}
   *
   * The generic implementation collects the matching keys then deletes them with `delete`; stores override it
   * with their native batch operation.
   * @override
   */
  async deleteMany(statement: string | WebdaQLQuery, params?: QueryParameters): Promise<number> {
    return this.deleteManyByKey(statement, params);
  }

  /**
   * Update in bulk: see {@link Repository.updateMany}
   *
   * The generic implementation collects the matching keys then patches them with `patch`; stores override it
   * with their native batch operation.
   * @override
   */
  async updateMany(statement: string | WebdaQLQuery, params?: QueryParameters): Promise<number> {
    return this.updateManyByKey(statement, params);
  }

  abstract query(
    query: string,
    params?: QueryParameters
  ): Promise<{ results: InstanceType<T>[]; continuationToken?: string }>;
  abstract iterate(query: string, params?: QueryParameters): AsyncGenerator<InstanceType<T>, any, any>;

  /** @override */
  configureAggregation(options: Partial<AggregationOptions>): void {
    for (const [key, value] of Object.entries(options)) {
      if (value !== undefined) {
        (this.aggregationOptions as any)[key] = value;
      }
    }
  }

  /**
   * Keep the full generic signature here (not `spec: any`): concrete repositories are used
   * directly in code and tests, and must expose the typed rows.
   * @override
   */
  async aggregate<
    const G extends readonly PropertyPaths<InstanceType<T>>[] = [],
    const M extends Record<string, MetricSpec<InstanceType<T>>> = Record<string, MetricSpec<InstanceType<T>>>
  >(
    spec: AggregationSpec<InstanceType<T>, G, M>,
    params?: QueryParameters
  ): Promise<AggregationResult<AggregatedRow<InstanceType<T>, G, M>>> {
    const { toAggregationQuery } = await import("@webda/ql");
    return this.executeAggregation(toAggregationQuery(spec as any, params));
  }

  /**
   * Run a validated aggregation
   *
   * Backends override it to aggregate natively, and call super for the shapes they cannot translate.
   * The default streams iterate() into the in-memory Aggregator, under the fallback policy.
   * @param query - the validated aggregation
   * @returns the rows
   */
  protected async executeAggregation(query: AggregationQuery): Promise<AggregationResult<any>> {
    await this.checkAggregationFallback(query, "the backend has no native aggregation");
    return { rows: await this.aggregateInMemory(query), native: false };
  }

  /**
   * Apply the fallback policy before aggregating in memory
   * @param query - the aggregation
   * @param reason - why it cannot run natively
   * @throws AggregationError AGGREGATION_NOT_NATIVE when the policy is deny
   */
  protected async checkAggregationFallback(query: AggregationQuery, reason: string): Promise<void> {
    const { fallback, warn } = this.aggregationOptions;
    if (fallback === "allow") return;
    const model = (this.model as any)?.Metadata?.Identifier ?? this.model?.name;
    const message = `Aggregation on ${model} grouped by [${query.groupBy.join(", ")}] runs in memory: ${reason}`;
    if (fallback === "deny") {
      const { AggregationError } = await import("@webda/ql");
      throw new AggregationError("AGGREGATION_NOT_NATIVE", message);
    }
    const shape = `${query.groupBy.join(",")}|${reason}`;
    if (!this.warnedAggregations.has(shape)) {
      this.warnedAggregations.add(shape);
      warn?.(message);
    }
  }

  /**
   * Aggregate by streaming the filtered items
   * @param query - the aggregation
   * @returns the rows
   */
  protected async aggregateInMemory(query: AggregationQuery): Promise<Record<string, unknown>[]> {
    const { Aggregator } = await import("@webda/ql");
    const aggregator = new Aggregator(query, this.aggregationOptions.maxGroups);
    for await (const item of this.iterate(query.filter.toString())) {
      aggregator.add(item);
    }
    return aggregator.rows();
  }
  abstract deleteItemFromCollection<
    K extends Extract<PropertyPaths<InstanceType<T>, any[]>, keyof InstanceType<T>>,
    L extends keyof ArrayElement<InstanceType<T>[K]>
  >(
    uuid: PrimaryKeyType<InstanceType<T>>,
    collection: K,
    index: number,
    itemWriteConditionField?: L,
    itemWriteCondition?: ArrayElement<InstanceType<T>[K]>[L]
  ): Promise<void>;
  abstract upsertItemToCollection<
    K extends Extract<PropertyPaths<InstanceType<T>, any[]>, keyof InstanceType<T>>,
    L extends keyof ArrayElement<InstanceType<T>[K]>
  >(
    uuid: PrimaryKeyType<InstanceType<T>>,
    collection: K,
    item: ArrayElement<InstanceType<T>[K]> | JSONed<ArrayElement<InstanceType<T>[K]>>,
    index?: number,
    itemWriteConditionField?: ArrayElement<InstanceType<T>[K]> extends object ? L : never,
    itemWriteCondition?: ArrayElement<InstanceType<T>[K]> extends object
      ? (object & ArrayElement<InstanceType<T>[K]>)[L]
      : ArrayElement<InstanceType<T>[K]>
  ): Promise<void>;
  abstract removeAttribute<L extends PropertyPaths<InstanceType<T>>, K extends PropertyPaths<InstanceType<T>>>(
    uuid: PrimaryKeyType<InstanceType<T>>,
    attribute: K,
    conditionField?: L | null,
    condition?: PropertyPathType<InstanceType<T>, L> | JSONed<PropertyPathType<InstanceType<T>, L>>
  ): Promise<void>;
  abstract get(primaryKey: PrimaryKeyType<InstanceType<T>>): Promise<Helpers<InstanceType<T>>>;
  abstract create(data: Helpers<InstanceType<T>>, save?: boolean): Promise<InstanceType<T>>;
  abstract patch<K extends PropertyPaths<InstanceType<T>>>(
    primaryKey: PK<InstanceType<T>, InstanceType<T>[typeof WEBDA_PRIMARY_KEY][number]>,
    data: Partial<InstanceType<T>>,
    _conditionField?: K | null,
    _condition?: any
  ): Promise<void>;
  abstract update<K extends PropertyPaths<InstanceType<T>>>(
    data: Helpers<InstanceType<T>>,
    conditionField?: K | null,
    condition?: PropertyPathType<InstanceType<T>, K>
  ): Promise<void>;
  abstract delete<K extends PropertyPaths<InstanceType<T>>>(
    uuid: PrimaryKeyType<InstanceType<T>>,
    conditionField?: K | null,
    condition?: PropertyPathType<InstanceType<T>, K> | JSONed<PropertyPathType<InstanceType<T>, K>>
  ): Promise<void>;
  abstract exists(uuid: PrimaryKeyType<InstanceType<T>>): Promise<boolean>;

  /** @override */
  on<K extends keyof InstanceType<T>[typeof WEBDA_EVENTS]>(
    event: K,
    listener: (data: InstanceType<T>[typeof WEBDA_EVENTS][K]) => void
  ): void {
    if (!this.events.has(event)) {
      this.events.set(event, new Set());
    }
    this.events.get(event)!.add(listener as any);
  }

  /** @override */
  once<K extends keyof InstanceType<T>[typeof WEBDA_EVENTS]>(
    event: K,
    listener: (data: InstanceType<T>[typeof WEBDA_EVENTS][K]) => void
  ): void {
    const wrapper = (d: any) => {
      listener(d);
      this.off(event, wrapper as any);
    };
    this.on(event, wrapper as any);
  }

  /** @override */
  off<K extends keyof InstanceType<T>[typeof WEBDA_EVENTS]>(
    event: K,
    listener: (data: InstanceType<T>[typeof WEBDA_EVENTS][K]) => void
  ): void {
    this.events.get(event)?.delete(listener as any);
  }

  /**
   * Max-listeners hint kept for Node `EventEmitter` API compatibility. Not
   * enforced — repositories use an unbounded `Set` per event.
   */
  protected maxListeners = 100;

  /**
   * EventEmitter-compatibility alias for {@link off}. Consumers that treat a
   * repository as a Node `EventEmitter` (e.g. `@webda/runtime` `EventIterator`)
   * call `removeListener`.
   * @param event - the event name
   * @param listener - the listener to remove
   */
  removeListener<K extends keyof InstanceType<T>[typeof WEBDA_EVENTS]>(
    event: K,
    listener: (data: InstanceType<T>[typeof WEBDA_EVENTS][K]) => void
  ): void {
    this.off(event, listener);
  }

  /**
   * EventEmitter-compatibility shim. Returns the max-listeners hint.
   * @returns the current max-listeners hint
   */
  getMaxListeners(): number {
    return this.maxListeners;
  }

  /**
   * EventEmitter-compatibility shim. Records the max-listeners hint (no enforcement).
   * @param n - the new hint value
   * @returns this for chaining
   */
  setMaxListeners(n: number): this {
    this.maxListeners = n;
    return this;
  }

  /**
   * Emit an event to all registered listeners and await their completion.
   * @param event - The event name to emit
   * @param data - The event payload
   */
  async emit<K extends keyof InstanceType<T>[typeof WEBDA_EVENTS]>(
    event: K,
    data: InstanceType<T>[typeof WEBDA_EVENTS][K]
  ): Promise<void> {
    if (!this.events.has(event)) {
      return;
    }
    await Promise.all([...this.events.get(event)!].map(fn => fn(data)));
  }
}
