import * as assert from "node:assert";
import type { Repository } from "./repository.js";

/**
 * Options of {@link checkCreateWithoutPrimaryKey}
 */
export interface CreateWithoutPrimaryKeyOptions {
  /**
   * Data of the item to create, without its primary key
   *
   * @param index - unique index of the creation, to build unique values
   */
  data: (index: number) => any;
  /**
   * Read the raw record stored by the backend under a key
   *
   * @param key - storage key
   * @returns the raw record, or undefined when nothing is stored under the key
   */
  readStored: (key: string) => Promise<any | undefined>;
  /**
   * Primary key field generated by the model
   *
   * @default "uuid"
   */
  keyField?: string;
}

/**
 * Check that creating an item without its primary key persists the key generated by the model
 *
 * For each repository, creates an item without the key, with the key `undefined` and with the key `null`,
 * then checks the key is generated, the backend stored the record under it with the key inside,
 * the item can be read back with the same key and nothing was stored under "undefined" or "null".
 *
 * It is a plain function rather than a test suite so store packages can share it without
 * duplicating test classes across module resolutions.
 *
 * @param repos - repositories to check, e.g. the store EventRepository and the raw backend repository
 * @param options - data factory and raw backend reader
 */
export async function checkCreateWithoutPrimaryKey(
  repos: Repository<any>[],
  options: CreateWithoutPrimaryKeyOptions
): Promise<void> {
  const keyField = options.keyField ?? "uuid";
  const keys = new Set<string>();
  let index = 0;
  for (const repo of repos) {
    for (const variant of [{}, { [keyField]: undefined }, { [keyField]: null }]) {
      const item: any = await repo.create({ ...options.data(index++), ...variant });
      const key = item[keyField];
      assert.ok(key, `a ${keyField} should be generated`);
      assert.ok(!["undefined", "null"].includes(String(key)), `the generated ${keyField} should not be '${key}'`);
      assert.ok(!keys.has(key), `the generated ${keyField} should be unique`);
      keys.add(key);
      // The backend stored the record under the generated key, with the key inside
      const stored = await options.readStored(key);
      assert.ok(stored, `the record should be stored under the generated ${keyField}`);
      assert.strictEqual(stored[keyField], key);
      // Reading it back keeps the key
      assert.strictEqual((await repo.get(key))[keyField], key);
    }
  }
  assert.strictEqual(await options.readStored("undefined"), undefined, "nothing should be stored under 'undefined'");
  assert.strictEqual(await options.readStored("null"), undefined, "nothing should be stored under 'null'");
}
