import * as assert from "node:assert";
import type { Repository } from "./repository.js";

/**
 * Options of {@link checkCreateWithoutPrimaryKey}
 */
export interface CreateWithoutPrimaryKeyOptions {
  /**
   * Data of the item to create, without its primary key
   *
   * @param index - unique index of the creation, to build unique values
   */
  data: (index: number) => any;
  /**
   * Read the raw record stored by the backend under a key
   *
   * @param key - storage key
   * @returns the raw record, or undefined when nothing is stored under the key
   */
  readStored: (key: string) => Promise<any | undefined>;
  /**
   * Primary key field generated by the model
   *
   * @default "uuid"
   */
  keyField?: string;
}

/**
 * Check that creating an item without its primary key persists the key generated by the model
 *
 * For each repository, creates an item without the key, with the key `undefined` and with the key `null`,
 * then checks the key is generated, the backend stored the record under it with the key inside,
 * the item can be read back with the same key and nothing was stored under "undefined" or "null".
 *
 * It is a plain function rather than a test suite so store packages can share it without
 * duplicating test classes across module resolutions.
 *
 * @param repos - repositories to check, e.g. the store EventRepository and the raw backend repository
 * @param options - data factory and raw backend reader
 */
export async function checkCreateWithoutPrimaryKey(
  repos: Repository<any>[],
  options: CreateWithoutPrimaryKeyOptions
): Promise<void> {
  const keyField = options.keyField ?? "uuid";
  const keys = new Set<string>();
  let index = 0;
  for (const repo of repos) {
    for (const variant of [{}, { [keyField]: undefined }, { [keyField]: null }]) {
      const item: any = await repo.create({ ...options.data(index++), ...variant });
      const key = item[keyField];
      assert.ok(key, `a ${keyField} should be generated`);
      assert.ok(!["undefined", "null"].includes(String(key)), `the generated ${keyField} should not be '${key}'`);
      assert.ok(!keys.has(key), `the generated ${keyField} should be unique`);
      keys.add(key);
      // The backend stored the record under the generated key, with the key inside
      const stored = await options.readStored(key);
      assert.ok(stored, `the record should be stored under the generated ${keyField}`);
      assert.strictEqual(stored[keyField], key);
      // Reading it back keeps the key
      assert.strictEqual((await repo.get(key))[keyField], key);
    }
  }
  assert.strictEqual(await options.readStored("undefined"), undefined, "nothing should be stored under 'undefined'");
  assert.strictEqual(await options.readStored("null"), undefined, "nothing should be stored under 'null'");
}

/**
 * Dataset of {@link checkAggregation}: nulls, missing attributes, a non-numeric `points`,
 * nested `team.name`, booleans. Lowercase ASCII strings only, so collations agree.
 */
export const AGGREGATION_DATASET: Record<string, any>[] = [
  { uuid: "a1", kind: "bug", team: { name: "core" }, points: 3, score: 10, label: "delta", done: true },
  { uuid: "a2", kind: "bug", team: { name: "core" }, points: 5, score: null, label: "alpha", done: false },
  { uuid: "a3", kind: "feature", team: { name: "web" }, points: null, score: 7, label: "charlie", done: false },
  { uuid: "a4", kind: "feature", team: { name: "web" }, points: "8", score: 2, label: "bravo", done: true },
  { uuid: "a5", kind: "chore", points: 1, label: "echo", done: false },
  { uuid: "a6", kind: null, team: { name: "core" }, points: 2, score: 4, label: "alpha", done: false },
  { uuid: "a7", team: { name: "ops" }, points: 13, score: 1, label: "foxtrot", done: true }
];

/**
 * Hand-computed expectations over {@link AGGREGATION_DATASET}; every backend must return exactly these rows
 */
export const AGGREGATION_CASES: { name: string; spec: any; rows: Record<string, unknown>[] }[] = [
  { name: "global count", spec: { metrics: { n: { count: "*" } } }, rows: [{ n: 7 }] },
  {
    name: "global over nothing",
    spec: {
      filter: "label = 'zulu'",
      metrics: { n: { count: "*" }, total: { sum: "points" }, mean: { avg: "points" }, lo: { min: "score" } }
    },
    rows: [{ n: 0, total: 0, mean: null, lo: null }]
  },
  {
    name: "count of a field skips null and missing",
    spec: { metrics: { withScore: { count: "score" }, withTeam: { count: "team.name" } } },
    rows: [{ withScore: 5, withTeam: 6 }]
  },
  {
    name: "null and missing keys form one group, first in ASC",
    spec: { groupBy: ["kind"], metrics: { n: { count: "*" } }, orderBy: [{ key: "kind", direction: "ASC" }] },
    rows: [
      { kind: null, n: 2 },
      { kind: "bug", n: 2 },
      { kind: "chore", n: 1 },
      { kind: "feature", n: 2 }
    ]
  },
  {
    name: "sum and avg ignore null and non-numeric",
    spec: {
      groupBy: ["kind"],
      metrics: { total: { sum: "points" }, mean: { avg: "points" } },
      orderBy: [{ key: "kind", direction: "ASC" }]
    },
    rows: [
      { kind: null, total: 15, mean: 7.5 },
      { kind: "bug", total: 8, mean: 4 },
      { kind: "chore", total: 1, mean: 1 },
      { kind: "feature", total: 0, mean: null }
    ]
  },
  {
    name: "min and max on numbers and strings, nested group",
    spec: {
      groupBy: ["team.name"],
      metrics: { lo: { min: "score" }, hi: { max: "score" }, first: { min: "label" } },
      orderBy: [{ key: "team.name", direction: "ASC" }]
    },
    rows: [
      { "team.name": null, lo: null, hi: null, first: "echo" },
      { "team.name": "core", lo: 4, hi: 10, first: "alpha" },
      { "team.name": "ops", lo: 1, hi: 1, first: "foxtrot" },
      { "team.name": "web", lo: 2, hi: 7, first: "bravo" }
    ]
  },
  {
    name: "count distinct grouped by boolean",
    spec: {
      groupBy: ["done"],
      metrics: { labels: { countDistinct: "label" }, n: { count: "*" } },
      orderBy: [{ key: "done", direction: "ASC" }]
    },
    rows: [
      { done: false, labels: 3, n: 4 },
      { done: true, labels: 3, n: 3 }
    ]
  },
  {
    name: "filter, order by alias and limit",
    spec: {
      filter: "label IN ['alpha', 'charlie', 'echo']",
      groupBy: ["team.name"],
      metrics: { n: { count: "*" } },
      orderBy: [{ key: "n", direction: "DESC" }],
      limit: 1
    },
    rows: [{ "team.name": "core", n: 2 }]
  },
  {
    name: "several group paths",
    spec: {
      groupBy: ["kind", "done"],
      metrics: { n: { count: "*" } },
      orderBy: [
        { key: "kind", direction: "ASC" },
        { key: "done", direction: "ASC" }
      ]
    },
    rows: [
      { kind: null, done: false, n: 1 },
      { kind: null, done: true, n: 1 },
      { kind: "bug", done: false, n: 1 },
      { kind: "bug", done: true, n: 1 },
      { kind: "chore", done: false, n: 1 },
      { kind: "feature", done: false, n: 1 },
      { kind: "feature", done: true, n: 1 }
    ]
  },
  {
    name: "order by metric then group, null last in DESC",
    spec: {
      groupBy: ["kind"],
      metrics: { n: { count: "*" } },
      orderBy: [
        { key: "n", direction: "DESC" },
        { key: "kind", direction: "DESC" }
      ],
      limit: 2
    },
    rows: [
      { kind: "feature", n: 2 },
      { kind: "bug", n: 2 }
    ]
  }
];

/**
 * Check a repository aggregates {@link AGGREGATION_DATASET} exactly like {@link AGGREGATION_CASES}
 *
 * The repository must be empty and keyed by `uuid`; the dataset is created in it.
 * @param repo - the repository to check
 * @param options - expected native flag, and case names to skip with a documented reason
 * @param options.native - the expected `native` flag of every result
 * @param options.skip - names of the cases to skip
 */
export async function checkAggregation(
  repo: Repository<any>,
  options: { native: boolean; skip?: string[] }
): Promise<void> {
  repo.configureAggregation({ fallback: "allow" });
  for (const item of AGGREGATION_DATASET) {
    await repo.create(structuredClone(item) as any);
  }
  for (const { name, spec, rows } of AGGREGATION_CASES) {
    if (options.skip?.includes(name)) continue;
    const res = await repo.aggregate(spec);
    assert.deepStrictEqual(res.rows, rows, name);
    assert.strictEqual(res.native, options.native, `${name}: native flag`);
  }
}
