/**
 * Rewrite pass: turns a {@link FilePlan} into TypeScript source text.
 *
 * This replaces the emit-time work done by `createAccessorTransformer` and
 * `createDeclarationAccessorTransformer`. Instead of synthesising AST nodes into
 * the compiler's emit pipeline, it writes ordinary TypeScript source containing
 * *asymmetric accessors* — `get createdAt(): Date` paired with
 * `set createdAt(value: string | number | Date)`.
 *
 * Asymmetric accessors have been legal TypeScript since 4.3, so any compiler
 * (tsc 6, tsgo 7, esbuild, swc, babel) will emit both the correct `.js` and the
 * correct `.d.ts` from this source with no plugin of any kind. That is the whole
 * point of the re-architecture.
 *
 * Rewriting is done by *text splicing* rather than AST printing, so comments,
 * formatting and unrelated syntax survive byte-for-byte.
 */
import { DEFAULT_COERCIONS, type ClassPlan, type CoercionRegistry, type FilePlan, type ResolvedCoercion } from "./types.ts";

/** A pending text replacement. */
interface Edit {
  start: number;
  end: number;
  text: string;
}

/**
 * Infer the indentation used by the original declaration so generated members
 * line up with their neighbours.
 * @param source - full file text
 * @param offset - offset of the declaration
 * @returns the leading whitespace of that line
 */
function indentAt(source: string, offset: number): string {
  const lineStart = source.lastIndexOf("\n", offset - 1) + 1;
  const line = source.slice(lineStart, offset);
  return /^[ \t]*$/.test(line) ? line : "  ";
}

/**
 * Render the getter/setter pair for one coercible field.
 * @param field - the resolved coercion
 * @param indent - indentation to apply
 * @param coercions - the active coercion registry
 * @returns generated TypeScript source
 */
function renderAccessor(field: ResolvedCoercion, indent: string, coercions: CoercionRegistry): string {
  const slot = `this[WEBDA_STORAGE][${JSON.stringify(field.name)}]`;
  const lines: string[] = [];

  // Preserve any JSDoc/comments that were attached to the original property by
  // re-attaching them to the getter, which is what editors surface on hover.
  lines.push(`${indent}get ${field.name}(): ${field.typeName} {`);
  lines.push(`${indent}  return ${slot};`);
  lines.push(`${indent}}`);

  lines.push(`${indent}set ${field.name}(value: ${field.setterType}) {`);
  if (field.coercionKind === "builtin") {
    const rule = coercions[field.typeName] ?? DEFAULT_COERCIONS[field.typeName];
    const coerced = rule.coerce("value");
    lines.push(`${indent}  ${slot} = value !== undefined && value !== null ? ${coerced} : value;`);
  } else {
    // `@WebdaAutoSetter` types absorb the raw value through their own `set()`.
    lines.push(`${indent}  if (value instanceof ${field.typeName}) {`);
    lines.push(`${indent}    ${slot} = value;`);
    lines.push(`${indent}    return;`);
    lines.push(`${indent}  }`);
    lines.push(`${indent}  const current = ${slot} ?? new ${field.typeName}();`);
    lines.push(`${indent}  current.set(value);`);
    lines.push(`${indent}  ${slot} = current;`);
  }
  lines.push(`${indent}}`);

  return lines.join("\n");
}

/**
 * Render the generated `toJSON`, which folds the hidden storage slot back into
 * a plain object. Matches the shape produced by the current transform.
 * @param indent - indentation to apply
 * @returns generated TypeScript source
 */
function renderToJSON(indent: string): string {
  return [
    ``,
    `${indent}/** Generated by @webda/codegen. */`,
    `${indent}toJSON(): Record<string, any> {`,
    `${indent}  const result: Record<string, any> = super.toJSON();`,
    `${indent}  for (const key of Object.keys(this)) {`,
    `${indent}    result[key] = (this as any)[key];`,
    `${indent}  }`,
    `${indent}  Object.assign(result, this[WEBDA_STORAGE]);`,
    `${indent}  return result;`,
    `${indent}}`
  ].join("\n");
}

/**
 * Collect the edits required for one class.
 * @param source - full file text
 * @param cls - the class plan
 * @param coercions - the active coercion registry
 * @returns the edits to apply
 */
function editsForClass(source: string, cls: ClassPlan, coercions: CoercionRegistry): Edit[] {
  const edits: Edit[] = [];

  for (const field of cls.fields) {
    const indent = indentAt(source, field.start);
    edits.push({
      start: field.start,
      end: field.end,
      text: renderAccessor(field, indent, coercions).slice(indent.length)
    });
  }

  if (cls.isModel && !cls.hasToJSON) {
    const indent = indentAt(source, cls.fields[0].start);
    edits.push({ start: cls.membersEnd, end: cls.membersEnd, text: renderToJSON(indent) });
  }

  return edits;
}

/**
 * Apply a plan to its source file and return the rewritten text.
 * @param plan - the file plan
 * @param source - original file text
 * @param storageModule - module specifier providing `WEBDA_STORAGE`
 * @param coercions - the active coercion registry
 * @returns rewritten TypeScript source
 */
export function rewrite(
  plan: FilePlan,
  source: string,
  storageModule = "@webda/models",
  coercions: CoercionRegistry = DEFAULT_COERCIONS
): string {
  const edits: Edit[] = [];
  for (const cls of plan.classes) {
    edits.push(...editsForClass(source, cls, coercions));
  }

  if (!plan.hasStorageImport) {
    if (plan.storageNamedInsertPos !== undefined) {
      // Merge into the existing `import { ... } from "<storageModule>"`.
      edits.push({
        start: plan.storageNamedInsertPos,
        end: plan.storageNamedInsertPos,
        text: ` WEBDA_STORAGE,`
      });
    } else {
      const stmt = `${plan.importInsertPos === 0 ? "" : "\n"}import { WEBDA_STORAGE } from ${JSON.stringify(storageModule)};`;
      edits.push({ start: plan.importInsertPos, end: plan.importInsertPos, text: stmt });
    }
  }

  // Apply back-to-front so earlier offsets stay valid.
  edits.sort((a, b) => b.start - a.start || b.end - a.end);

  let out = source;
  for (const e of edits) {
    out = out.slice(0, e.start) + e.text + out.slice(e.end);
  }
  return out;
}
