# main should be used for development and future v4 and v4-beta
# maintenance/v3 should be only used for maintenance tasks
name: "CI"

on:
  push:
    branches: [main, maintenance/v3.x]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [main, maintenance/v3.x]

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    # Cannot rely on Github Azure hosted action because of GCP connection
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: ["22", "24", "current"]
    name: Build with NodeJS v${{ matrix.node }}
    env:
      FORCE_COLOR: 1

    services:
      localstack:
        image: localstack/localstack:3.6.0 # Cannot use latest until we get an OSS license
        ports:
          - 4566:4566
        env:
          SERVICES: s3,sts,sqs,dynamodb,secretsmanager,logs

      mongodb:
        image: mongo
        ports:
          - 37017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: webda.io

      amqp:
        image: rabbitmq
        ports:
          - 5672:5672

    permissions:
      id-token: "write"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - uses: fsouza/fake-gcs-action@f8e805c9cef6056421b73390d078b2fb467b989c # v0.4.2
        with:
          version: "1.54.0"
          backend: memory
          location: "US-WEST2"
          public-host: "storage.gcs.127.0.0.1.nip.io:4443"
          external-url: "http://storage.gcs.127.0.0.1.nip.io:4443"
          scheme: http

      - uses: "google-github-actions/setup-gcloud@aa5489c8933f4cc7a4f7d45035b3b1440c9c10db" # v3.0.1
        with:
          install_components: "cloud-firestore-emulator,pubsub-emulator"

      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144

      - name: "Start GCP emulators"
        run: |
          gcloud --quiet beta emulators pubsub start --host-port=127.0.0.1:8085 &
          gcloud --quiet alpha emulators firestore start --host-port=127.0.0.1:8289 &

      - name: Runs Elasticsearch
        uses: elastic/elastic-github-actions/elasticsearch@98431b45a60cbb6ace481778827bc8e11f12fd65
        with:
          stack-version: 8.15.0
          security-enabled: false
          wait: 0

      - name: Setup postgresql
        uses: Softwarepark/postgresql-action@92b6750bf30f39d64489c77d38a1675dfb4a8bc0 # v2
        with:
          postgresql version: "15" # See https://hub.docker.com/_/postgres for available versions
          postgresql password: webda.io
          postgresql user: webda.io
          postgresql db: webda.io
          postgresql init scripts: packages/postgres/test/sql

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build # Build is required as we use sample-app for some tests
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"

      - name: Run tests
        run: pnpm run test
        env:
          NODE_OPTIONS: "--max-old-space-size=6144"
          GCS_API_ENDPOINT: http://storage.gcs.127.0.0.1.nip.io:4443
          PUBSUB_EMULATOR_HOST: 127.0.0.1:8085
          FIRESTORE_EMULATOR_HOST: 127.0.0.1:8289
          GOOGLE_APPLICATION_CREDENTIALS: /home/runner/work/webda.io/webda.io/packages/gcp/webda-test.json

      - name: Check for circular dependencies
        run: pnpm run deps:graph

      - name: Lint
        run: pnpm run lint

      - name: Check with mocha
        run: pnpm run test:mocha

      - name: Check with jest
        run: pnpm run test:jest

      - name: Check with bun
        run: pnpm run test:bun

      - name: CodeCov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
