name: "update docs"

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: pnpm install && cd docs && pnpm install

      - name: Build docs
        env:
          NODE_OPTIONS: "--max-old-space-size=8192"
        run: pnpm run docs

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@c15a2b0ec4f14477a295a7eda11b8f1dbdeceead # 4.8.0
        with:
          branch: gh-pages
          folder: docs/dist
