# Use to update webda.module.json on release-please branches
on:
  push:
    branches:
      - release-please/*

permissions:
  contents: write
  pull-requests: write

name: update-webda-module
jobs:
  ensure-module:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Build
        run: pnpm install && pnpm run build
